import{ArrowUpRight,MapPin,Phone,Scissors,Star}from"lucide-react";
const photos=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWny17FbmSWny4DBmsi1seieiEdfdGpQAV8Ep6bed4pSn3hwQar0tHT_OZMRAMvp8CkDY2Sx54ogPYT985Qo50jsRWIVYBLiYKvuIxq_j41yiBlbUoyzHuWXOx7tj8tYI_hscd8H=w530-h298-k-no","https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlA0i1GAut1VLdj8W_aumrBE1LOq6bn55d0pFY0aR_MrLJB1mIJFGtR9Xmus-cUfpRmg0GPM-N0wxk9VMAF7o59oNKqHcjgi_dj1C9W2Wdtk2PUqvFcQLUHOKcXLN8KLLWhJ3Gq=w224-h398-k-no","https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=eUa4hP1QJPkNTWz71VMkPw&cb_client=maps_sv.tactile.gps&w=224&h=298&yaw=324.93097&pitch=0&thumbfov=100"];
const services=[["Strzyżenie","Indywidualne dopasowanie formy do włosów i stylu."],["Stylizacja","Wykończenie fryzury z uwzględnieniem naturalnej tekstury."],["Koloryzacja","Kolor dopasowany do typu urody i kondycji włosów."],["Włosy kręcone","Świadoma praca z lokami i falami oraz ich naturalnym skrętem."],["Grzywka","Precyzyjne cięcie dopasowane do twarzy."],["Suszenie i wykończenie","Dopracowana stylizacja na co dzień lub okazję."]];
export default function Home(){const maps="https://www.google.com/maps/dir/?api=1&destination=Promie%C5%84%204%2C%2051-659%20Wroc%C5%82aw";return <main><nav><b>MOONLU<span>•</span></b><div className="links"><a href="#uslugi">Usługi</a><a href="#galeria">Galeria</a><a href="#o-nas">O salonie</a><a href="#kontakt">Kontakt</a></div><a className="topbtn" href="tel:+48713452000">Umów wizytę ↗</a></nav>
<section className="hero"><div><small>● SALON FRYZJERSKI · WROCŁAW</small><h1>Włosy, które<br/><i>mają charakter.</i></h1><p>MOONLU to kameralny salon Moniki Leszczyńskiej. Świadoma praca z włosami, naturalnym skrętem i stylem, który pasuje do Ciebie.</p><div className="actions"><a className="btn dark" href="tel:+48713452000"><Phone size={16}/>71 345 20 00</a><a className="btn" href={maps} target="_blank">Jak dojechać <MapPin size={16}/></a></div><div className="meta"><b><Star size={14} fill="currentColor"/> 5,0</b><span>12 opinii Google</span><span>Promień 4, Wrocław</span></div></div><div className="visual"><img className="big" src={photos[0]} alt="MOONLU"/><img className="small" src={photos[1]} alt="Stylizacja MOONLU"/><div className="badge"><Scissors size={20}/>HAIR<br/>WITH CARE</div></div></section>
<section className="intro" id="o-nas"><small>01 / O SALONIE</small><div><h2>Małe miejsce.<br/><i>Duża dbałość o szczegóły.</i></h2><p>W MOONLU najważniejsze są włosy i osoba, która siedzi na fotelu. Każda usługa zaczyna się od rozmowy i poznania potrzeb włosów. Szczególną uwagę poświęcamy włosom kręconym i falowanym.</p></div><strong className="score">5,0<small>średnia ocen<br/>Google</small></strong></section>
<section className="section" id="uslugi"><small>02 / USŁUGI</small><h2>To, czego potrzebują<br/><i>Twoje włosy.</i></h2><div className="services">{services.map((s,i)=><article key={s[0]}><small>0{i+1}</small><h3>{s[0]}</h3><p>{s[1]}</p><ArrowUpRight/></article>)}</div></section>
<section className="section gallery" id="galeria"><small>03 / GALERIA</small><h2>Efekty, które<br/><i>mówią same za siebie.</i></h2><div className="grid"><img src={photos[1]} alt="Galeria MOONLU"/><img src={photos[0]} alt="Galeria MOONLU"/><div><Scissors/><b>Naturalny efekt.</b><span>Precyzja bez przesady.</span></div><img src={photos[2]} alt="Salon MOONLU"/></div></section>
<section className="section reviews"><small>04 / OPINIE</small><h2>12 opinii.<br/><i>Jedna ocena: 5,0.</i></h2><div className="reviewgrid">{["Polecam Panią Monikę, to prawdziwa ekspertka od kręconych włosów. Jestem bardzo zadowolona.","Pani Monika jest perfekcjonistką w swoim fachu. Potrafi zadbać o wymagające włosy.","Stylizacja włosów, koloryzacja, przycinanie grzywki i suszenie."].map((t,i)=><article key={i}><span>★★★★★</span><p>“{t}”</p><b>{["Marta","Magda Nowakowska","Kornelia"][i]}</b></article>)}</div></section>
<section className="contact" id="kontakt"><div><small>05 / KONTAKT</small><h2>Wpadnij do<br/><i>MOONLU.</i></h2><p>Promień 4<br/>51-659 Wrocław</p><a className="phone" href="tel:+48713452000">71 345 20 00</a></div><div className="card"><b>● Otwarte · zamknięcie 18:00</b><p><MapPin/> Promień 4, 51-659 Wrocław</p><a href={maps} target="_blank">Wyznacz trasę <ArrowUpRight/></a></div></section><footer><b>MOONLU<span>•</span></b><span>© {new Date().getFullYear()} Monika Leszczyńska</span><a href="#top">Na górę ↑</a></footer></main>}